// data.js
// ============================================================
// Cấu trúc: Year → Volume
// Chương được parse TỰ ĐỘNG từ file .txt khi người dùng mở volume
// → KHÔNG cần liệt kê từng chương ở đây
//
// Quy tắc file .txt:
//   - Mỗi chương bắt đầu bằng dòng:  # Tên chương
//   - Ảnh chèn vào bằng cú pháp:     [img:ten_anh.png]
//     hoặc                        [HÌNH ẢNH: images/ten_anh.png]
//   - Dòng trống phân cách đoạn văn
//   - Phần / Section dùng:            ## Tên phần  (tùy chọn)
// ============================================================

const LIBRARY = [
  {
    id: "nam-1",
    label: "Năm 1",
    volumes: [
      {
        id: "nam-1-vol-1",
        label: "Volume 1",
        translator: "",
        file: "content/Nam-1/Volume 1/Volume 1.txt",
        imagesDir: "content/Nam-1/Volume 1/images/",
      },
      {
        id: "nam-1-vol-2",
        label: "Volume 2",
        translator: "",
        file: "content/Nam-1/Volume 2/Volume 2.txt",
        imagesDir: "content/Nam-1/Volume 2/images/",
      },
      {
        id: "nam-1-vol-3",
        label: "Volume 3",
        translator: "",
        file: "content/Nam-1/Volume 3/Volume 3.txt",
        imagesDir: "content/Nam-1/Volume 3/images/",
      },
      {
        id: "nam-1-vol-4",
        label: "Volume 4",
        translator: "",
        file: "content/Nam-1/Volume 4/Volume 4.txt",
        imagesDir: "content/Nam-1/Volume 4/images/",
      },
      {
        id: "nam-1-vol-5",
        label: "Volume 5",
        translator: "",
        file: "content/Nam-1/Volume 5/Volume 5.txt",
        imagesDir: "content/Nam-1/Volume 5/images/",
      },
      {
        id: "nam-1-vol-6",
        label: "Volume 6",
        translator: "",
        file: "content/Nam-1/Volume 6/Volume 6.txt",
        imagesDir: "content/Nam-1/Volume 6/images/",
      },
      {
        id: "nam-1-vol-7",
        label: "Volume 7",
        translator: "",
        file: "content/Nam-1/Volume 7/Volume 7.txt",
        imagesDir: "content/Nam-1/Volume 7/images/",
      },
      {
        id: "nam-1-vol-8",
        label: "Volume 8",
        translator: "",
        file: "content/Nam-1/Volume 8/Volume 8.txt",
        imagesDir: "content/Nam-1/Volume 8/images/",
      },
      {
        id: "nam-1-vol-9",
        label: "Volume 9",
        translator: "",
        file: "content/Nam-1/Volume 9/Volume 9.txt",
        imagesDir: "content/Nam-1/Volume 9/images/",
      },
      {
        id: "nam-1-vol-10",
        label: "Volume 10",
        translator: "",
        file: "content/Nam-1/Volume 10/Volume 10.txt",
        imagesDir: "content/Nam-1/Volume 10/images/",
      },
      {
        id: "nam-1-vol-11",
        label: "Volume 11",
        translator: "",
        file: "content/Nam-1/Volume 11/Volume 11.txt",
        imagesDir: "content/Nam-1/Volume 11/images/",
      },
    ],
  },

  {
    id: "nam-2",
    label: "Năm 2",
    volumes: [
      {
        id: "nam-2-vol-1",
        label: "Volume 1",
        translator: "",
        file: "content/Nam-2/Volume 1/Volume 1.txt",
        imagesDir: "content/Nam-2/Volume 1/images/",
      },
      {
        id: "nam-2-vol-2",
        label: "Volume 2",
        translator: "",
        file: "content/Nam-2/Volume 2/Volume 2.txt",
        imagesDir: "content/Nam-2/Volume 2/images/",
      },
      {
        id: "nam-2-vol-3",
        label: "Volume 3",
        translator: "Fisherman",
        file: "content/Nam-2/Volume 3/Volume 3.txt",
        imagesDir: "content/Nam-2/Volume 3/images/",
      },
      {
        id: "nam-2-vol-4",
        label: "Volume 4",
        translator: "",
        file: "content/Nam-2/Volume 4/Volume 4.txt",
        imagesDir: "content/Nam-2/Volume 4/images/",
      },
      {
        id: "nam-2-vol-5",
        label: "Volume 5",
        translator: "",
        file: "content/Nam-2/Volume 5/Volume 5.txt",
        imagesDir: "content/Nam-2/Volume 5/images/",
      },
      {
        id: "nam-2-vol-6",
        label: "Volume 6",
        translator: "",
        file: "content/Nam-2/Volume 6/Volume 6.txt",
        imagesDir: "content/Nam-2/Volume 6/images/",
      },
      {
        id: "nam-2-vol-7",
        label: "Volume 7",
        translator: "",
        file: "content/Nam-2/Volume 7/Volume 7.txt",
        imagesDir: "content/Nam-2/Volume 7/images/",
      },
      {
        id: "nam-2-vol-8",
        label: "Volume 8",
        translator: "",
        file: "content/Nam-2/Volume 8/Volume 8.txt",
        imagesDir: "content/Nam-2/Volume 8/images/",
      },
      {
        id: "nam-2-vol-9",
        label: "Volume 9",
        translator: "",
        file: "content/Nam-2/Volume 9/Volume 9.txt",
        imagesDir: "content/Nam-2/Volume 9/images/",
      },
      {
        id: "nam-2-vol-10",
        label: "Volume 10",
        translator: "",
        file: "content/Nam-2/Volume 10/Volume 10.txt",
        imagesDir: "content/Nam-2/Volume 10/images/",
      },
      {
        id: "nam-2-vol-11",
        label: "Volume 11",
        translator: "",
        file: "content/Nam-2/Volume 11/Volume 11.txt",
        imagesDir: "content/Nam-2/Volume 11/images/",
      },
      {
        id: "nam-2-vol-12",
        label: "Volume 12",
        translator: "",
        file: "content/Nam-2/Volume 12/Volume 12.txt",
        imagesDir: "content/Nam-2/Volume 12/images/",
      },
    ],
  },

  {
    id: "nam-3",
    label: "Năm 3",
    volumes: [
      {
        id: "nam-3-vol-1",
        label: "Volume 1",
        translator: "",
        file: "content/Nam-3/Volume 1/Volume 1.txt",
        imagesDir: "content/Nam-3/Volume 1/images/",
      },
      {
        id: "nam-3-vol-2",
        label: "Volume 2",
        translator: "",
        file: "content/Nam-3/Volume 2/Volume 2.txt",
        imagesDir: "content/Nam-3/Volume 2/images/",
      },
      {
        id: "nam-3-vol-3",
        label: "Volume 3",
        translator: "",
        file: "content/Nam-3/Volume 3/Volume 3.txt",
        imagesDir: "content/Nam-3/Volume 3/images/",
      },
    ],
  },
];

// ── Nhân vật được highlight tự động ────────────────────────────
const CHARACTERS = [
  "Ai Morishita",
  "Airi Sakura",
  "Akane Tachibana",
  "Akito Miyake",
  "Albert Yamada",
  "Arisu Sakayanagi",
  "Chiaki Matsushita",
  "Chie Hoshinomiya",
  "Chihiro Shiranami",
  "Daichi Ishizaki",
  "Fūka Kiryūin",
  "Fuuka Kiryuuin",
  "Haruka Hasebe",
  "Haruki Yamauchi",
  "Hayato Kitō",
  "Hayato Kito",
  "Hideo Sotomura",
  "Hiyori Shiina",
  "Honami Ichinose",
  "Ichika Amasawa",
  "Ikuto Kiriyama",
  "Kakeru Ryūen",
  "Kakeru Ryuuen",
  "Kanji Ike",
  "Katsunori Shiba",
  "Kayano Onodera",
  "Kazuma Sakagami",
  "Kazuomi Hōsen",
  "Kazuomi Housen",
  "Kei Karuizawa",
  "Ken Sudō",
  "Ken Sudou",
  "Kikyō Kushida",
  "Kikyou Kushida",
  "Kiyotaka Ayanokōji",
  "Kiyotaka Ayanokouji",
  "Kokoro Inogashira",
  "Kyōgo Komiya",
  "Kyougo Komiya",
  "Kōhei Katsuragi",
  "Kouhei Katsuragi",
  "Mako Amikura",
  "Manabu Horikita",
  "Masayoshi Hashimoto",
  "Masumi Kamuro",
  "Maya Satō",
  "Maya Satou",
  "Mio Ibuki",
  "Miyabi Nagumo",
  "Nazuna Asahina",
  "Nene Mori",
  "Reo Kondō",
  "Reo Kondou",
  "Riku Utomiya",
  "Rokusuke Kōenji",
  "Rokusuke Koenji",
  "Ryūji Kanzaki",
  "Ryuuji Kanzaki",
  "Sae Chabashira",
  "Sakurako Tsubaki",
  "Satoru Kaneda",
  "Satsuki Shinohara",
  "Sayo Andō",
  "Sayo Ando",
  "Suzune Horikita",
  "Sō Shibata",
  "Sou Shibata",
  "Takuya Yagami",
  "Teruhiko Yukimura",
  "Tomonari Mashima",
  "Tsubasa Nanase",
  "Tsukishiro",
  "Vương Mỹ Vũ",
  "Vuong My Vu",
  "Yahiko Totsuka",
  "Yuki Himeno",
  "Yukitsu Kusuda",
  "Yume Kobashi",
  "Yōsuke Hirata",
  "Yousuke Hirata",

  // alias ngắn để highlight mềm hơn trong bản dịch
  "Ayanokouji",
  "Horikita",
  "Karuizawa",
  "Kei",
  "Hirata",
  "Kushida",
  "Nanase",
  "Sakayanagi",
  "Ryuuen",
  "Ryuen",
  "Ichinose",
  "Koenji",
  "Kouenji",
  "Sudou",
  "Sudo",
  "Chabashira",
  "Mashima",
  "Ibuki",
  "Hoshinomiya",
  "Sakura",
  "Miyake",
  "Hasebe",
  "Ike",
  "Katsuragi",
  "Nagumo",
  "Kiryuuin",
  "Kiriyuuin",
  "Amasawa",
  "Housen",
  "Kanzaki",
  "Shiina",
  "Komiya",
  "Shibata",
  "Yagami",
];
